testSubjectNames = [
    "Alver",
    "Scarlet",
    "Estella",
    "Villith",
    "Wiltio",
    "Seth",
    "Shigo",
    "Avis",
    "Alvis",
    "Eiran",
    "Sylus",
    "Nora",
    "Clare",
    "Alberu",
    "Nikolai",
    "Brandon",
    "Elisa",
    "Annika",
    "Lucas",
    "Nadia",
]

testSubjectIDs = [
    "QW2834",
    "ZX4501",
    "UV9203",
    "BC7654",
    "ER1298",
    "MN4312",
    "PL7645",
    "XK9087",
    "TE3409",
    "LU5160",
    "JD2741",
    "HR8392",
    "YT0538",
    "DF6209",
    "OP3948",
    "NB5720",
    "AK1703",
    "SM4825",
    "VG1930",
    "WL3094",
]

testSubjectIDwName = list(zip(testSubjectNames, testSubjectIDs))

testSubjectReason = [
    "Oh, I  was out collecting samples.",
    "I was collecting the scraps.",
    "I went outside to transport the samples.",
    "I went out to collect resources.",
    "I was hunting the anomalies.",
    "I went out to get milk!",
    "I was following my friend.",
    "I wanted to sketch the landscapes",
    "I was looking for stranded survivors",
    "The shelter has structural issues, overcrowding, and violence. It's no longer safe.",
    "We're out of essential resources like food, water, and medical supplies.",
    "I need medical treatment that's only available outside the shelter.",
    "I need to find my family and friends to ensure their safety.",
    "This confined space is affecting my mental health. I need a change.",
    "We need more information about the outside situation to plan our next steps.",
    "Someone needs to scout safe routes or places for potential relocation.",
    "I want to help those in more dire situations outside the shelter.",
    "Bravery is needed to confront and solve the root problems.",
]
